/* Conectado como usuário system */

ALTER SESSION SET CONTAINER = PDBORCL21;

-- Cria o tablespace TBS_RELACIONAL
CREATE TABLESPACE tbs_relacional 
    DATAFILE '/u01/app/oracle/oradata/ORCL21/pdborcl21/TBS_RELACIONAL.dbf'
    SIZE 1M 
    AUTOEXTEND ON NEXT 10M 
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

-- Cria o usuário relacional
CREATE USER relacional IDENTIFIED BY relacional001 DEFAULT TABLESPACE tbs_relacional;
GRANT CONNECT, RESOURCE TO relacional;
GRANT UNLIMITED TABLESPACE TO relacional;

-- Cria o tablespace TBS_STAGE_AREA
CREATE TABLESPACE tbs_stage_area
    DATAFILE '/u01/app/oracle/oradata/ORCL21/pdborcl21/TBS_STAGE_AREA.dbf'
    SIZE 1M
    AUTOEXTEND ON NEXT 10M
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

-- Cria o usuário stagearea
CREATE USER stagearea IDENTIFIED BY stagearea001 DEFAULT TABLESPACE tbs_stage_area;
GRANT CONNECT, RESOURCE TO stagearea;
GRANT UNLIMITED TABLESPACE TO stagearea;

-- Cria o tablespace TBS_DATA_WAREHOUSE
CREATE TABLESPACE tbs_data_warehouse
    DATAFILE '/u01/app/oracle/oradata/ORCL21/pdborcl21/TBS_DATA_WAREHOUSE.dbf'
    SIZE 1M
    AUTOEXTEND ON NEXT 10M
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE tbs_fato_part_t1
    DATAFILE '/u01/app/oracle/oradata/ORCL21/pdborcl21/TBS_FATO_PART_T1.dbf'
    SIZE 1M
    AUTOEXTEND ON NEXT 10M
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE tbs_fato_part_t2
    DATAFILE '/u01/app/oracle/oradata/ORCL21/pdborcl21/TBS_FATO_PART_T2.dbf'
    SIZE 1M
    AUTOEXTEND ON NEXT 10M
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE tbs_fato_part_t3
    DATAFILE '/u01/app/oracle/oradata/ORCL21/pdborcl21/TBS_FATO_PART_T3.dbf'
    SIZE 1M
    AUTOEXTEND ON NEXT 10M
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE tbs_fato_part_t4
    DATAFILE '/u01/app/oracle/oradata/ORCL21/pdborcl21/TBS_FATO_PART_T4.dbf'
    SIZE 1M
    AUTOEXTEND ON NEXT 10M
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

-- Cria o usuário datawarehouse
CREATE USER datawarehouse IDENTIFIED BY datawarehouse001 DEFAULT TABLESPACE tbs_data_warehouse;
GRANT CONNECT, RESOURCE TO datawarehouse;
GRANT UNLIMITED TABLESPACE TO datawarehouse;